plugins {
    id 'java'
    id 'war'

}
group 'com.example'
version '1.0-SNAPSHOT'
repositories {
    mavenCentral()
    maven { url 'https://repo.maven.apache.org/maven2' } // возможно, требуется другой репозиторий
}

ext {
    junitVersion = '5.10.0'
}

sourceCompatibility = '11'
targetCompatibility = '11'

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

dependencies {
    implementation 'jakarta.persistence:jakarta.persistence-api:3.1.0'
    implementation 'org.eclipse.persistence:eclipselink:3.0.0'
    implementation 'org.hibernate:hibernate-core:5.6.15.Final'
    implementation 'org.postgresql:postgresql:42.5.4'
    implementation 'com.mchange:c3p0:0.9.5.5'
    implementation 'jakarta.enterprise:jakarta.enterprise.cdi-api:4.0.1'
    implementation 'jakarta.validation:jakarta.validation-api:3.0.2'
    implementation 'jakarta.ejb:jakarta.ejb-api:4.0.1'
    implementation 'jakarta.faces:jakarta.faces-api:3.0.0'
    implementation 'jakarta.servlet:jakarta.servlet-api:6.0.0'
    implementation 'jakarta.persistence:jakarta.persistence-api:3.1.0'
    implementation 'jakarta.platform:jakarta.jakartaee-web-api:9.0.0'
    implementation 'jakarta.json:jakarta.json-api:2.1.1'
    implementation 'jakarta.json.bind:jakarta.json.bind-api:3.0.0'
    implementation 'org.postgresql:postgresql:42.6.0'
    implementation 'org.hibernate:hibernate-core:6.2.6.Final'
    implementation 'org.primefaces:primefaces:12.0.0:jakarta'
    implementation 'com.google.guava:guava:31.0.1-jre'
    implementation 'org.apache.commons:commons-lang3:3.12.0'
    implementation 'com.google.code.gson:gson:2.10.1'
    runtimeOnly 'org.flywaydb:flyway-gradle-plugin:9.16.1'
    compileOnly 'org.projectlombok:lombok:1.18.26'
    annotationProcessor 'org.projectlombok:lombok:1.18.26'
    testCompileOnly 'org.projectlombok:lombok:1.18.26'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.26'

    implementation 'javax.xml.bind:jaxb-api:2.3.1'
    implementation 'org.glassfish.jaxb:jaxb-runtime:2.3.1'
}

test {
    useJUnitPlatform()
}


import javax.xml.parsers.DocumentBuilderFactory

task xml {
    group = "verification"
    description = "Check all .xml files in project directory"

    doLast {
        def xmlDir = projectDir
        def factory = DocumentBuilderFactory.newInstance()
        def hasErrors = false

        xmlDir.eachFileRecurse { file ->
            if (file.name.endsWith(".xml")) {
                try {
                    factory.newDocumentBuilder().parse(file)
                    println "${file.path} correct"
                } catch (Exception e) {
                    println "Error in file ${file.path}: ${e.message}"
                    hasErrors = true
                }
            }
        }
        if (hasErrors) {
            throw new GradleException("There is an errors in .xml files!")
        }
    }
}

task scp(dependsOn: build) {
    group = "deployment"
    description = "Build project and send it to chosen server by scp"

    doLast {
        def user = project.hasProperty("name") ? project.property("name") : "admin"
        def host = project.hasProperty("host") ? project.property("host") : "localhost"
        def remoteDir = "/home/${user}/deploy/"
        def localFile = file("build/libs/${project.name}-${version}.war") // или конкретный .jar

        if (!localFile.exists()) {
            throw new GradleException("file not found: ${localFile}")
        }

        println "Sending ${localFile.name} on ${user}@${host}:${remoteDir}"

        def result = exec {
            commandLine 'scp', localFile.absolutePath, "${user}@${host}:${remoteDir}"
        }

        println "Sending is completed"
    }
}

task music(dependsOn: build) {
    group = "fun"
    description = "play the song if project build successfully"

    doLast {
        def audioFile = file("zvuk-kogda-bolshoy-svin-hryukaet.mp3") // путь к твоему файлу

        if (!audioFile.exists()) {
            throw new GradleException("File ${audioFile.name} not found")
        }
        exec {
            commandLine 'cmd', '/c', "start", '', audioFile.absolutePath
        }
    }
}

task native2ascii {
    group = "localization"
    description = ".properties files in ASCII (native2ascii)"

    def inputDir = file("src/main/resources/localization")
    def outputDir = file("$buildDir/localization")

    doLast {
        if(!outputDir.exists()){
            throw new GradleException("File ${outputDir} not found")
        }
                ant.native2ascii(
                        encoding: "UTF-8",
                        src: inputDir,
                        dest: outputDir
                )
        println "Convert results in $outputDir"
    }
}

task diff {
    group = 'vsl'
    description = 'check diffs adn do commit if it possible'

    def notAllowedFile = file("src/main/resources/not-allowed-file.txt")

    doLast {
        if (!notAllowedFile.exists()) {
            throw new GradleException("File ${notAllowedFile.name} not found")
        }
        def notAllowedPatterns = notAllowedFile.readLines()
        def changedFiles = "git diff --name-only".execute().text.readLines()

        if (changedFiles.isEmpty()) {
            println "There are no files to commit"
            return
        }

        println "Changed files:\n${changedFiles.join('\n')}"
        println "Changed files:\n${notAllowedPatterns.join('\n')}"

        def notAllowedFiles = changedFiles.findAll { fileName ->
            notAllowedPatterns.any { pattern ->
                fileName ==~ pattern.replace(".", "\\.").replace("*", ".*")
            }
        }

        if (!notAllowedFiles.isEmpty()) {
            throw new GradleException("Not allowed changes:\n${notAllowedFiles.join('\n')}")
        }

        println "do commit"

        "git add .".execute().waitFor()
        def commitProcess = ["git", "commit", "-m", "commit by Gradle"].execute()
        commitProcess.waitFor()
        println commitProcess.text + "done"

    }
}